# Generated by Django 5.1.4 on 2025-01-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpheus', '0002_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='configuration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Field'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('ranking', 'Ranking'), ('linear_scale', 'Linear Scale'), ('date', 'Date Picker'), ('time', 'Time Picker'), ('file', 'File Upload'), ('matrix', 'Matrix/Grid'), ('image_choice', 'Image Choice'), ('slider', 'Slider'), ('signature', 'Signature'), ('color', 'Color Picker'), ('geolocation', 'Geolocation'), ('percentage', 'Percentage Allocation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('survey', 'order'), name='unique_question_order'),
        ),
    ]
